### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by msheldon83** [waffleio/gfm-task-lists#4]
hello

**Comment by kellihsf** [comment]
![bear.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56241220b728ed1d0009af87/125516c66e82c728ace21e0d46ea919b31c0cfeb9ffbb049a15ee4d6730472212c54f77a7383e678eb1779590e0c4da9170d5b42fef99b37b4f46d2ede0356b49b381d66cc2f10a4b2831abc08ba22884c8db4b9884ad2a5.gif)
